apiVersion: v1
kind: Secret
metadata:
  name: azure-csc-account
  namespace: monitoring
  labels:
    name: azure-csc-account
data:
  azure_sp_app_id: {{ "aaa" | b64encode }}
  azure_sp_secret: {{ "bbb" | b64encode }}
  azure_sp_tenant_id: {{ "ccc" | b64encode }}