apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account
  namespace: monitoring
  labels:
    name: azure-storage-account
data:
  azure_storage_account: {{ azure["storage_account"] | b64encode }}
  azure_storage_account_key: {{ azure["storage_account_key"] | b64encode }}
