apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
  namespace: monitoring
  labels:
    run: autoscaler
spec:
  replicas: 1
  selector:
    run: autoscaler
  template:
    metadata:
      labels:
        run: autoscaler
        openai/do-not-drain: "true"
      name: autoscaler
    spec:
      nodeSelector:
        role: "worker"
      containers:
      - name: autoscaler
        image: wbuchwalter/autoscaler
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: azure-csc-account
              key: azure_sp_app_id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-csc-account
              key: azure_sp_secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-csc-account
              key: azure_sp_tenant_id
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: kubernetes.default
        - name: DATADOG_TAGS
          value: env:sci
        command:
            - python
            - main.py
            - --resource-group 
            - rg-dmp-k8s-dmpcluster-dev-westus2
            - --container-service-name 
            - dmpcluster
            - -vvv
            - --over-provision
            - "0"
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default
